// packages/autocomplete-react/src/Dropdown.tsx
/** @jsx h */

import { h } from 'preact';

import { reverseHighlightAlgoliaHit } from '@francoischalifour/autocomplete-presets';

import {
  AutocompleteSuggestion,
  GetItemProps,
  GetMenuProps,
} from '@francoischalifour/autocomplete-core';

interface DropdownProps {
  isOpen: boolean;
  status: string;
  suggestions: Array<AutocompleteSuggestion<any>>;
  getItemProps: GetItemProps<any>;
  getMenuProps: GetMenuProps;
}

export const Dropdown = (props: DropdownProps) => {
  return (
    <div
      className={[
        'algolia-autocomplete-dropdown',
        status === 'stalled' && 'algolia-autocomplete-dropdown--stalled',
        status === 'error' && 'algolia-autocomplete-dropdown--errored',
      ]
        .filter(Boolean)
        .join(' ')}
      hidden={!props.isOpen}
    >
      {props.isOpen && (
        <div className="algolia-autocomplete-dropdown-container">
          {props.suggestions.map((suggestion, index) => {
            const { source, items } = suggestion;

            return (
              <section
                key={`result-${index}`}
                className="algolia-autocomplete-suggestions"
              >
                {items.length > 0 && (
                  <ul {...props.getMenuProps()}>
                    {items.map((item, index) => {
                      return (
                        <li
                          key={`item-${index}`}
                          className="algolia-autocomplete-suggestions-item"
                          {...props.getItemProps({
                            item,
                            source,
                            tabIndex: 0,
                          })}
                        >
                          <div
                            dangerouslySetInnerHTML={{
                              __html: reverseHighlightAlgoliaHit({
                                hit: item,
                                attribute: 'query',
                              }),
                            }}
                          />
                        </li>
                      );
                    })}
                  </ul>
                )}
              </section>
            );
          })}
        </div>
      )}
    </div>
  );
};

// packages/autocomplete-vue/Dropdown.vue
<template>
  <div
    :hidden="!isOpen"
    :class="{
      'algolia-autocomplete-dropdown': true,
      'algolia-autocomplete-dropdown--stalled': status === 'stalled',
      'algolia-autocomplete-dropdown--errored': status === 'error',
    }"
  >
    <div class="algolia-autocomplete-dropdown-container">
      <section
        v-for="({ source, items }, index) in suggestions"
        :key="'result-' + index"
        class="algolia-autocomplete-suggestions"
      >
        <ul v-if="items.length > 0" v-bind="getMenuProps()">
          <li
            v-for="(item, index) in items"
            :key="'item-' + index"
            class="algolia-autocomplete-suggestions-item"
            v-bind="getItemProps({ item, source, tabIndex: 0 })"
            @mousemove="getItemProps({ item, source, tabIndex: 0 }).onMouseMove"
            @mousedown="getItemProps({ item, source, tabIndex: 0 }).onMouseDown"
            @click="getItemProps({ item, source, tabIndex: 0 }).onClick"
          >
            <!-- TODO: improve the props above -->
            <div
              v-html="
                reverseHighlightAlgoliaHit({
                  hit: item,
                  attribute: 'query',
                })
              "
            />
          </li>
        </ul>
      </section>
    </div>
  </div>
</template>

<script>
import { reverseHighlightAlgoliaHit } from '../autocomplete-presets';

export default {
  props: {
    isOpen: { type: Boolean, required: true },
    suggestions: { type: Array, required: true },
    status: { type: String, required: true },
    getItemProps: { type: Function },
    getMenuProps: { type: Function },
  },
  methods: {
    reverseHighlightAlgoliaHit,
  },
};
</script>
